name: Test

on:
  push: {branches: main}
  pull_request: {branches: main}
  repository_dispatch:
  workflow_dispatch:

jobs:
  integration_test:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.pair.otp-version}} / Elixir ${{matrix.pair.elixir-version}}
    strategy:
      matrix:
        pair:
          - otp-version: '22.2'
            elixir-version: '1.7.4'
          - otp-version: '22.2'
            elixir-version: '1.8.2'
          - otp-version: '21.x'
            elixir-version: '1.9.4'
    steps:
      - uses: actions/checkout@v2
      - name: Use actions/setup-elixir
        id: setup-elixir
        uses: ./
        with:
          otp-version: ${{matrix.pair.otp-version}}
          elixir-version: ${{matrix.pair.elixir-version}}
      - name: Output runtime versions
        run: echo "Elixir ${{steps.setup-elixir.outputs.elixir-version}} / OTP ${{steps.setup-elixir.outputs.otp-version}}"
      - name: Run Mix project tests
        run: |-
          cd test-project
          mix deps.get
          mix test
