name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  integration_test:
    runs-on: ubuntu-latest
    name: OTP ${{matrix.pair.otp}} / Elixir ${{matrix.pair.elixir}}
    strategy:
      matrix:
        pair:
          - otp: '21.x'
            elixir: '1.9.4'
          - otp: '22.2'
            elixir: '1.10.4'
          - otp: '24.2'
            elixir: '1.13.1'
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.pair.otp}}
          elixir-version: ${{matrix.pair.elixir}}
      - name: Install dependencies
        run: mix deps.get --only test
      - run: mix deps.compile
      - name: Run tests
        run: mix test
